#mysql -u ismael -p -h 127.0.0.1 -D counting_db
version: '3.8'
services:
  counting-app:
    build: .
    container_name: counting_app
    volumes:
      - ./People-Counting-in-Real-Time:/app
      - /dev/video0:/dev/video0  # Para acceder a la webcam
#      - ./People-Counting-in-Real-Time:/app/data
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=ismael
      - DB_PASSWORD=ismael
      - DB_NAME=counting_db
    ports:
      - "8080:8080"
      - "8081:8081"
volumes:
 app:
